name: Build AUR Package in ArchLinux Docker

on:
  workflow_dispatch:
    inputs:
      aur:
        type: string
        description: 'aur 链接'
      clean:
        type: boolean
        description: '运行器扩容（磁盘空间不足时勾选）'
  # push:
  #   branches:
  #     - main

jobs:
  build-aur:
    runs-on: ubuntu-latest
    env:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8

    steps:
      #- name: 检出仓库代码
      #  uses: actions/checkout@v4
      - name: 汉化
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-zh-hans

      - name: 扩容（可选）
        if: 
        uses: rokibhasansagar/slimhub_actions@main

      - name: apt 添加 docker 源密钥
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

      - name: apt 添加 docker 源
        run: |
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

      - name: 安装 Docker
        run: |
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: 拉取 Arch Linux 镜像
        run: |
          docker pull archlinux:latest

      - name: 在 Arch Linux 容器内构建 AUR 包
        run: |
          # 1. 启动容器，并将当前工作目录挂载到容器的 /workspace
          docker run --name arch-build -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest bash -c "
            set -ex
            # 2. 更新系统并安装基础开发工具
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel git sudo
            # 3. 添加构建用户，防止用 root 构建
            useradd -m builder
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            su builder <<'EOF'
              sudo pacman-key --init
              sudo pacman-key --populate
              sudo mkdir -p /workspace/build
              sudo chown -R $(whoami):$(whoami) /workspace
              cd /workspace
              # 4. 克隆 AUR 包（以 yay 为例，可替换为目标包）
              git clone ${{ inputs.aur }} build
              cd build
              # 5. 构建包
              makepkg -si --noconfirm
              # 6. 将产物复制出来
              cp *.pkg.tar.zst /workspace/
            EOF
          "

      - name: 提取 AUR 包产物到宿主机
        run: |
          # 拷贝产物（如有需要，可修改为目标产物名）
          ls -lh *.pkg.tar.zst

      # 可选：上传构建的包到 GitHub Actions 的构件区
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: aur-packages
          path: "*.pkg.tar.zst"