name: 调中文测试
on:
  workflow_dispatch:
jobs:
  chinese:
    runs-on: ubuntu-latest
    env:
      LANG: zh_CN.UTF-8
    steps:
      - name: 一键中文化
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-zh-hans
      - name: 修改系统语言
        run: |
          echo "export LANG=zh_CN.UTF-8" >> ~/.bashrc
          source ~/.bashrc
      - name: 测试1
        run: locale
      - name: 测试2
        run: sudo apt install firefox
