name: 下载 Docker 镜像

on:
  workflow_dispatch:
      inputs:
        image:
          type: string
          description: '镜像链接'
        name:
          type: string
          description: '文件名'


jobs:
  download-image:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取指定 Docker 镜像
        run: docker pull ${{ inputs.image }}

      - name: 保存镜像为指定文件
        run: docker save ${{ inputs.image }} -o ${{ inputs.name }}.tar

      - name: 上传镜像文件（可选）
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.name }}.tar
