name: 普通下载
on:
  workflow_dispatch:
    inputs:
      bt:
        description: '文件链接'
        type: string
      name:
        description: '压缩文件名'
        default: download
        type: string
      fname:
        description: '保存文件名'
        type: string

jobs:
  download:
    name: 下载
    runs-on: ubuntu-latest
    steps:
      - name: 下载（指定文件名）
        if: ${{ inputs.fname != '' }}
        run: |
          mkdir download
          cd download
          wget ${{ inputs.bt }} -O ${{ inputs.fname }}

      - name: 下载（默认文件名）
        if: ${{ inputs.fname == '' }}
        run: |
          mkdir download
          cd download
          wget ${{ inputs.bt }}

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: download
