name: GD File Transfer

on:
  workflow_dispatch: # 允许你手动点击按钮触发

jobs:
  transfer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-state: '3.x'

    - name: Install gdown
      run: |
        pip install gdown

    - name: Download from Google Drive
      run: |
        # 将下面的 FILE_ID 替换 your_file_id
        # 如果下载的是文件夹，把 gdown 换成 gdown --folder
        cd download
        gdown --id "1ODjdjrIDi76Mn7ekZ_GBK42ZsR7vdH58" --remaining-ok

    - name: Upload to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: transferred-file
        path: |
          download
        #retention-days: 1 # 下载完就失效，保护隐私
