name: PVZ Portable Build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        include:
          - name: amd64
            os: ubuntu-22.04
          - name: arm64
            os: ubuntu-22.04-arm
    container:
      image: ubuntu:20.04
    env:
      DEBIAN_FRONTEND: noninteractive
  
    steps:  
      - name: 安装依赖
        run: |
          apt-get update
          apt install -y git build-essential gcc-10 g++-10 cmake ninja-build pkg-config libogg-dev libjpeg-dev libopenmpt-dev libpng-dev libvorbis-dev libmpg123-dev libsdl2-dev libfmt-dev

          # 把 gcc/g++ 默认指向 10
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
          update-alternatives --install /usr/bin/c++  c++  /usr/bin/g++-10 100

      - name: 检出代码
        run: |
          git clone https://github.com/TC999/PvZ-Portable.git --depth=1 --single-branch -b 20.04 .

      - name: 配置
        run: |
          mkdir build
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Releas

      - name: 编译
        run: |
          cmake --build build

      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: pvz-port-20.04-${{ matrix.name }}
          path: build/pvz-portable
